version: '3'  

services: 
    frontend: 
      image: ninja-front
      build:
        context: ../ninja-ranking-frontend-react
        dockerfile: Dockerfile
      ports: 
        - 3000:3000
      volumes:
        - ../ninja-ranking-frontend-react/:/app
      container_name: ninja-front
      depends_on: 
        - backend

    backend: 
      image: ninja-back
      build:
        context: ./
        dockerfile: Dockerfile
      ports: 
        - 3001:3001
      environment:
        - DATABASE_URL=postgresql://postgres:example@db:5432/postgres
      container_name: ninja-back
      depends_on:
        - db

    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=example
      ports:
        - 5432:5432
      volumes:
        - ./data:/var/lib/postgresql/data
        - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      container_name: ninja-db

    web:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - backend
        - frontend
      container_name: ninja-proxy