put http://localhost/api/tournaments/12
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1paWthIiwiaWQiOjEsImlhdCI6MTU4NzcwMDUwMX0.qRkgnkiEPIB0hArc5-KOB6SRyD0oIXM8ZGHOus0VSYY

{
  "active": true
}
